name: quicksosapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  logger: ^2.6.1
  cloud_firestore: ^6.0.2
  flutter_osm_plugin: ^1.4.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  image: ^4.5.4
  provider: ^6.1.5+1
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.3
  supabase_flutter: ^2.10.3
  geolocator: ^14.0.1
  http: ^1.6.0
  path: ^1.9.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
     - assets/images/
  fonts:
    - family: samsungsharpsans
      fonts:
        - asset: assets/fonts/samsungsharpsans.otf
